function ya=envelope(sa,bw);
global Fd Fs;
x=sa;m=length(x);
N=length(x);
M=N*(Fd/Fs);
zbw=(N/4)-M-1;
ss=fft(x);
bww=ones(1,M+1);
bwz=zeros(1,zbw);
sk=[bwz bww bww bwz bwz bww bww bwz];
x=ss.*sk;
x=real(ifft(x));
x=abs(x);
bw=bw;
N=length(x);
M=N*(bw/Fs);
zbw=(N/2)-M-1;
ss=fft(x);
bww=ones(1,M+1);
bwz=zeros(1,zbw);
sk=[bww bwz bwz bww];
sx=ss.*sk;
ya=real(ifft(sx));